application: perfectpet4me
version: 1
runtime: go
api_version: go1

handlers:
  - url: /index\.html
    static_files: templates/index.html
    upload: templates/index\.html

  - url: .*/css
    static_dir: templates/css

  - url: .*/fonts
    static_dir: templates/fonts

  - url: .*/ico
    static_dir: templates/ico

  - url: .*/img
    static_dir: templates/img

  - url: .*/js
    static_dir: templates/js

  - url: /.*
    script: _go_app
    login: required